server:
  port: 8080

spring:
  application:
    name: dynamic-datasource-seata
  datasource:
    dynamic:
      primary: order  #设置默认的数据源或者数据源组,默认值即为master
      strict: true  #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      seata: true    #开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata-mode: AT #支持XA及AT模式,默认AT
      datasource:
        order:
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:3306/seata_order?characterEncoding=utf8
          #useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          driver-class-name: com.mysql.jdbc.Driver
#          schema: classpath:db/schema-order.sql  # 配置则生效,自动初始化表结构
        account:
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:3306/seata_account?characterEncoding=utf8
          driver-class-name: com.mysql.jdbc.Driver
#          schema: classpath:db/schema-account.sql  # 配置则生效,自动初始化表结构
        product:
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:3306/seata_product?characterEncoding=utf8
          driver-class-name: com.mysql.jdbc.Driver
#          schema: classpath:db/schema-product.sql  # 配置则生效,自动初始化表结构
#        test:
#          username: sa
#          password: ""
#          url: jdbc:h2:mem:test
#          driver-class-name: org.h2.Driver
#          seata: false #这个数据源不需要seata
seata:
  enabled: true
  application-id: applicationName
  tx-service-group: my_test_tx_group
  #一定要是false
  enable-auto-data-source-proxy: false
  service:
    vgroup-mapping:
      #key与上面的tx-service-group的值对应
      my_test_tx_group: default
    grouplist:
      #seata-server地址仅file注册中心需要
      default: 127.0.0.1:8091
  config:
    type: file
  registry:
    type: file
